// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GrindstoneTempoIntegration.Domain.Grindstone;
//
//    var grindstoneDatabase = GrindstoneDatabase.FromJson(jsonString);

namespace GrindstoneTempoIntegration.Domain.Grindstone
{
    using System;
    using System.Collections.Generic;

    public class S
    {
        public string SelectedViewId { get; set; }
    }

    public class A
    {
        public string i { get; set; }
        public string n { get; set; }
        public int s { get; set; }
    }

    public class E
    {
        public string i { get; set; }
        public string a { get; set; }
        public string n { get; set; }
    }

    public class T
    {
        public string i { get; set; }
        public string n { get; set; }
    }

    public class P
    {
        public string i { get; set; }
        public string n { get; set; }
        public DateTime a { get; set; }
    }

    public class R
    {
        public string i { get; set; }
        public string t { get; set; }
        public string p { get; set; }
        public DateTime e { get; set; }
        public string n { get; set; }
        public DateTime s { get; set; }
    }

    public class F
    {
        public List<A> a { get; set; }
        public List<E> e { get; set; }
        public List<T> t { get; set; }
        public List<P> p { get; set; }
        public List<R> r { get; set; }
    }

    public class Gdit
    {
        public string s { get; set; }
        public string e { get; set; }
    }

    public class C
    {
        public string p { get; set; }
        public string w { get; set; }
        public int v { get; set; }
    }

    public class A2
    {
        public string i { get; set; }
        public string n { get; set; }
        public int s { get; set; }
        public List<C> c { get; set; }
    }

    public class I
    {
        public string v { get; set; }
        public string t { get; set; }
    }

    public class C2
    {
        public string p { get; set; }
        public string w { get; set; }
        public int v { get; set; }
        public List<I> i { get; set; }
    }

    public class P2
    {
        public string s { get; set; }
    }

    public class D
    {
        public string i { get; set; }
        public string n { get; set; }
        public int s { get; set; }
        public List<C2> c { get; set; }
        public P2 p { get; set; }
    }

    public class Dci
    {
        public string v { get; set; }
        public string t { get; set; }
    }

    public class Rgc
    {
        public string i { get; set; }
        public string n { get; set; }
        public string c { get; set; }
        public string a { get; set; }
        public string dc { get; set; }
        public string ds { get; set; }
        public int? m { get; set; }
        public List<Dci> dci { get; set; }
    }

    public class I2
    {
        public string v { get; set; }
        public string t { get; set; }
    }

    public class C3
    {
        public string p { get; set; }
        public string w { get; set; }
        public List<I2> i { get; set; }
    }

    public class V
    {
        public string t { get; set; }
        public string i { get; set; }
        public string n { get; set; }
        public int s { get; set; }
        public List<C3> c { get; set; }
    }

    public class GrindstoneDatabase
    {
        public string i { get; set; }
        public S s { get; set; }
        public string p { get; set; }
        public string u { get; set; }
        public int t { get; set; }
        public F f { get; set; }
        public List<string> gdid { get; set; }
        public List<Gdit> gdit { get; set; }
        public A2 a { get; set; }
        public D d { get; set; }
        public List<Rgc> rgc { get; set; }
        public List<V> v { get; set; }
    }

}
